"""Leakage-safe P3H residual states for a likelihood-power ambiguity family.

Every generalized-Bayes target must forecast the same already-opened response
history with its own posterior predictive law.  Its raw PIT sequence and P3H
residual state are therefore target-specific.  No nominal residual state is
copied or replayed across likelihood powers.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
import math

import numpy as np

from .reference import (
    DyadicPolyaTreePredictiveLaw,
    DyadicPolyaTreeResidualModel,
    DyadicPolyaTreeState,
    ExactPosterior,
    SequentialReferencePosterior,
    predictive_cdf,
)


P3H4_RESIDUAL_FAMILY_METHOD = (
    "model-specific-likelihood-power-prequential-raw-pit-family-v1"
)
P3H4_OBSERVATION_ORDER = (
    "initial-development-stored-order-then-acquisition-reveal-order"
)
P3H4_STATE_BINDING = "exact-engine-posterior-residual-law-object-binding"


def _readonly(values: np.ndarray) -> np.ndarray:
    array = np.ascontiguousarray(values, dtype=float)
    if not np.all(np.isfinite(array)):
        raise ValueError("P3H likelihood-power history must be finite")
    array.setflags(write=False)
    return array


def _history_commitment(actions: np.ndarray, targets: np.ndarray) -> str:
    digest = sha256()
    digest.update(P3H4_RESIDUAL_FAMILY_METHOD.encode("ascii"))
    digest.update(P3H4_OBSERVATION_ORDER.encode("ascii"))
    digest.update(np.asarray(actions.shape, dtype=np.int64).tobytes())
    digest.update(np.asarray(actions, dtype=np.float64).tobytes())
    digest.update(np.asarray(targets, dtype=np.float64).tobytes())
    return digest.hexdigest()


def _conditioned_history_commitment(
    conditioning_actions: np.ndarray,
    conditioning_targets: np.ndarray,
    residual_actions: np.ndarray,
    residual_targets: np.ndarray,
) -> str:
    digest = sha256()
    digest.update(P3H4_RESIDUAL_FAMILY_METHOD.encode("ascii"))
    digest.update(P3H4_OBSERVATION_ORDER.encode("ascii"))
    digest.update(b"conditioning-prefix-then-residual-history")
    for role, actions, targets in (
        (b"conditioning", conditioning_actions, conditioning_targets),
        (b"residual", residual_actions, residual_targets),
    ):
        digest.update(role)
        digest.update(np.asarray(actions.shape, dtype=np.int64).tobytes())
        digest.update(np.asarray(actions, dtype=np.float64).tobytes())
        digest.update(np.asarray(targets, dtype=np.float64).tobytes())
    return digest.hexdigest()


@dataclass(frozen=True)
class LikelihoodPowerResidualModelState:
    """One posterior target and the residual law generated by that target."""

    likelihood_power: float
    engine: SequentialReferencePosterior
    posterior: ExactPosterior
    residual_state: DyadicPolyaTreeState
    residual_law: DyadicPolyaTreePredictiveLaw
    history_commitment: str

    def __post_init__(self) -> None:
        power = float(self.likelihood_power)
        if (
            not math.isfinite(power)
            or power != self.engine.likelihood_power
            or power != self.posterior.likelihood_power
            or self.posterior.bank_hash != self.engine.bank.stable_hash
            or self.residual_law.history_count != len(self.residual_state.raw_pits)
            or not self.history_commitment
        ):
            raise ValueError("P3H likelihood-power model state is inconsistent")

    @property
    def target_hash(self) -> str:
        return self.engine.target_hash

    @property
    def stable_hash(self) -> str:
        digest = sha256()
        for value in (
            P3H4_RESIDUAL_FAMILY_METHOD,
            self.target_hash,
            self.history_commitment,
            self.residual_state.stable_hash,
        ):
            digest.update(value.encode("ascii"))
        return digest.hexdigest()


@dataclass(frozen=True)
class LikelihoodPowerResidualFamily:
    """Power-sorted, history-bound posterior/residual family for acquisition."""

    model_states: tuple[LikelihoodPowerResidualModelState, ...]
    observation_count: int
    history_commitment: str
    conditioning_count: int = 0
    observation_order: str = P3H4_OBSERVATION_ORDER
    method: str = P3H4_RESIDUAL_FAMILY_METHOD
    state_binding: str = P3H4_STATE_BINDING

    def __post_init__(self) -> None:
        powers = tuple(item.likelihood_power for item in self.model_states)
        commitments = tuple(item.history_commitment for item in self.model_states)
        if (
            not self.model_states
            or isinstance(self.observation_count, bool)
            or self.observation_count <= 0
            or isinstance(self.conditioning_count, bool)
            or self.conditioning_count < 0
            or powers != tuple(sorted(set(powers)))
            or commitments != (self.history_commitment,) * len(self.model_states)
            or any(
                item.residual_law.history_count != self.observation_count
                for item in self.model_states
            )
            or not self.history_commitment
            or self.observation_order != P3H4_OBSERVATION_ORDER
            or self.method != P3H4_RESIDUAL_FAMILY_METHOD
            or self.state_binding != P3H4_STATE_BINDING
        ):
            raise ValueError("P3H likelihood-power residual family is invalid")

    @property
    def likelihood_powers(self) -> tuple[float, ...]:
        return tuple(item.likelihood_power for item in self.model_states)

    @property
    def residual_laws(self) -> tuple[DyadicPolyaTreePredictiveLaw, ...]:
        return tuple(item.residual_law for item in self.model_states)

    @property
    def stable_hash(self) -> str:
        digest = sha256()
        digest.update(self.method.encode("ascii"))
        digest.update(self.observation_order.encode("ascii"))
        digest.update(self.state_binding.encode("ascii"))
        digest.update(self.history_commitment.encode("ascii"))
        digest.update(np.asarray(
            [self.conditioning_count, self.observation_count], dtype=np.int64
        ).tobytes())
        for state in self.model_states:
            digest.update(state.stable_hash.encode("ascii"))
        return digest.hexdigest()


def _validated_engines(
    engines: tuple[SequentialReferencePosterior, ...],
) -> tuple[SequentialReferencePosterior, ...]:
    if not engines or any(
        not isinstance(engine, SequentialReferencePosterior) for engine in engines
    ):
        raise TypeError("P3H residual family requires reference posterior engines")
    ordered = tuple(sorted(engines, key=lambda engine: engine.likelihood_power))
    powers = tuple(engine.likelihood_power for engine in ordered)
    bank_hashes = {engine.bank.stable_hash for engine in ordered}
    transform_hashes = {
        engine.design_preconditioner.stable_hash
        if engine.design_preconditioner is not None
        else "raw-basis"
        for engine in ordered
    }
    if (
        len(set(powers)) != len(powers)
        or len(bank_hashes) != 1
        or len(transform_hashes) != 1
    ):
        raise ValueError(
            "P3H residual targets must have unique powers and one bank/design transform"
        )
    return ordered


def reconstruct_likelihood_power_residual_family(
    engines: tuple[SequentialReferencePosterior, ...],
    observed_actions: np.ndarray,
    observed_targets: np.ndarray,
    *,
    residual_model: DyadicPolyaTreeResidualModel | None = None,
) -> LikelihoodPowerResidualFamily:
    """Reconstruct target-specific states from one chronological opened history.

    At history position ``t``, engine ``eta`` first fits only positions before
    ``t``, evaluates its own raw predictive PIT for position ``t``, and only
    then admits that response.  The loop contains no future, candidate-pool or
    held-out response input.
    """

    ordered = _validated_engines(tuple(engines))
    actions, targets = SequentialReferencePosterior._validated_data(
        observed_actions, observed_targets
    )
    actions = _readonly(actions)
    targets = _readonly(targets).reshape(-1)
    commitment = _history_commitment(actions, targets)
    model = residual_model or DyadicPolyaTreeResidualModel()
    states: list[LikelihoodPowerResidualModelState] = []
    for engine in ordered:
        residual_state = model.prior_state()
        for index, target in enumerate(targets):
            posterior_before = (
                engine.prior_posterior()
                if index == 0
                else engine.fit_batch(actions[:index], targets[:index])
            )
            raw_pit = predictive_cdf(
                engine,
                posterior_before,
                actions[index : index + 1],
                np.asarray([target]),
                clip=None,
            )
            residual_state = model.update(residual_state, float(raw_pit[0]))
        posterior = engine.fit_batch(actions, targets)
        states.append(
            LikelihoodPowerResidualModelState(
                likelihood_power=engine.likelihood_power,
                engine=engine,
                posterior=posterior,
                residual_state=residual_state,
                residual_law=model.predictive_law(residual_state),
                history_commitment=commitment,
            )
        )
    return LikelihoodPowerResidualFamily(
        model_states=tuple(states),
        observation_count=len(targets),
        history_commitment=commitment,
    )


def reconstruct_conditioned_likelihood_power_residual_family(
    engines: tuple[SequentialReferencePosterior, ...],
    conditioning_actions: np.ndarray,
    conditioning_targets: np.ndarray,
    residual_actions: np.ndarray,
    residual_targets: np.ndarray,
    *,
    residual_model: DyadicPolyaTreeResidualModel | None = None,
) -> LikelihoodPowerResidualFamily:
    """Initialize each target after a base-only conditioning prefix.

    Conditioning responses fit the base posterior but never become residual
    PIT observations.  Residual observations are then forecast one at a time
    from the conditioning prefix plus their own strict residual prefix.
    """

    ordered = _validated_engines(tuple(engines))
    conditioning_x, conditioning_y = SequentialReferencePosterior._validated_data(
        conditioning_actions, conditioning_targets
    )
    residual_x, residual_y = SequentialReferencePosterior._validated_data(
        residual_actions, residual_targets
    )
    if conditioning_x.shape[1] != residual_x.shape[1]:
        raise ValueError("conditioning and residual feature dimensions must match")
    conditioning_x = _readonly(conditioning_x)
    conditioning_y = _readonly(conditioning_y).reshape(-1)
    residual_x = _readonly(residual_x)
    residual_y = _readonly(residual_y).reshape(-1)
    commitment = _conditioned_history_commitment(
        conditioning_x, conditioning_y, residual_x, residual_y
    )
    model = residual_model or DyadicPolyaTreeResidualModel()
    states: list[LikelihoodPowerResidualModelState] = []
    for engine in ordered:
        residual_state = model.prior_state()
        posterior = engine.fit_batch(conditioning_x, conditioning_y)
        for action, target in zip(residual_x, residual_y, strict=True):
            raw_pit = predictive_cdf(
                engine,
                posterior,
                action[None, :],
                np.asarray([target]),
                clip=None,
            )
            residual_state = model.update(residual_state, float(raw_pit[0]))
            posterior = engine.update_one(posterior, action, float(target))
        states.append(
            LikelihoodPowerResidualModelState(
                likelihood_power=engine.likelihood_power,
                engine=engine,
                posterior=posterior,
                residual_state=residual_state,
                residual_law=model.predictive_law(residual_state),
                history_commitment=commitment,
            )
        )
    return LikelihoodPowerResidualFamily(
        model_states=tuple(states),
        conditioning_count=len(conditioning_y),
        observation_count=len(residual_y),
        history_commitment=commitment,
    )


def advance_likelihood_power_residual_family(
    family: LikelihoodPowerResidualFamily,
    conditioning_actions: np.ndarray,
    conditioning_targets: np.ndarray,
    residual_actions: np.ndarray,
    residual_targets: np.ndarray,
    *,
    residual_model: DyadicPolyaTreeResidualModel | None = None,
) -> LikelihoodPowerResidualFamily:
    """Admit exactly one newly opened residual observation to every target."""

    if not isinstance(family, LikelihoodPowerResidualFamily):
        raise TypeError("P3H family advancement requires a frozen family")
    conditioning_x, conditioning_y = SequentialReferencePosterior._validated_data(
        conditioning_actions, conditioning_targets
    )
    residual_x, residual_y = SequentialReferencePosterior._validated_data(
        residual_actions, residual_targets
    )
    if (
        len(conditioning_y) != family.conditioning_count
        or len(residual_y) != family.observation_count + 1
        or conditioning_x.shape[1] != residual_x.shape[1]
    ):
        raise ValueError("P3H family advancement history length is invalid")
    prefix_commitment = (
        _history_commitment(residual_x[:-1], residual_y[:-1])
        if family.conditioning_count == 0
        else _conditioned_history_commitment(
            conditioning_x,
            conditioning_y,
            residual_x[:-1],
            residual_y[:-1],
        )
    )
    if prefix_commitment != family.history_commitment:
        raise ValueError("P3H family advancement prefix commitment changed")
    next_commitment = (
        _history_commitment(residual_x, residual_y)
        if family.conditioning_count == 0
        else _conditioned_history_commitment(
            conditioning_x, conditioning_y, residual_x, residual_y
        )
    )
    model = residual_model or DyadicPolyaTreeResidualModel()
    action = residual_x[-1]
    target = float(residual_y[-1])
    states: list[LikelihoodPowerResidualModelState] = []
    for state in family.model_states:
        raw_pit = predictive_cdf(
            state.engine,
            state.posterior,
            action[None, :],
            np.asarray([target]),
            clip=None,
        )
        next_residual = model.update(state.residual_state, float(raw_pit[0]))
        next_posterior = state.engine.update_one(
            state.posterior, action, target
        )
        states.append(
            LikelihoodPowerResidualModelState(
                likelihood_power=state.likelihood_power,
                engine=state.engine,
                posterior=next_posterior,
                residual_state=next_residual,
                residual_law=model.predictive_law(next_residual),
                history_commitment=next_commitment,
            )
        )
    return LikelihoodPowerResidualFamily(
        model_states=tuple(states),
        conditioning_count=family.conditioning_count,
        observation_count=family.observation_count + 1,
        history_commitment=next_commitment,
    )


__all__ = [
    "P3H4_OBSERVATION_ORDER",
    "P3H4_RESIDUAL_FAMILY_METHOD",
    "P3H4_STATE_BINDING",
    "LikelihoodPowerResidualFamily",
    "LikelihoodPowerResidualModelState",
    "advance_likelihood_power_residual_family",
    "reconstruct_conditioned_likelihood_power_residual_family",
    "reconstruct_likelihood_power_residual_family",
]
