"""Import-safe CERT.14 execution flags shared with the resident engine."""

P3F4_CERT14_FLOAT_FACTOR_BASIS_RESIDENT_TARGET_AUTHORIZED = False
P3F4_CERT14_RESIDENT_SMC_RUN_AUTHORIZED = False


__all__ = [
    "P3F4_CERT14_FLOAT_FACTOR_BASIS_RESIDENT_TARGET_AUTHORIZED",
    "P3F4_CERT14_RESIDENT_SMC_RUN_AUTHORIZED",
]
